version: '3'

vars:
  DOCKER_COMPOSE_FILE: docker compose.yml
  TERRAFORM_DIR: terraform
  KUBERNETES_DIR: kubernetes

tasks:
  install:
    desc: Install all dependencies
    cmds:
      - echo "Installing dependencies..."
      - if [ ! -f .env ]; then cp .env.example .env; fi
      - docker compose build
      - docker compose run --rm web yarn install


  dev:
    desc: Start development environment
    cmds:
      - echo "Starting development environment..."
      - docker compose up

  dev:down:
    desc: Stop development environment
    cmds:
      - echo "Stopping development environment..."
      - docker compose down

  test:
    desc: Run tests
    cmds:
      - echo "Running tests..."
      - docker compose run --rm web bundle exec rspec

  test:frontend:
    desc: Run frontend tests
    cmds:
      - echo "Running frontend tests..."
      - docker compose run --rm web yarn test

  lint:
    desc: Run all linters
    cmds:
      - task: lint:ruby
      - task: lint:typescript

  lint:ruby:
    desc: Run Ruby linters
    cmds:
      - echo "Running Ruby linters..."
      - docker compose run --rm web bundle exec rubocop

  lint:typescript:
    desc: Run TypeScript linters
    cmds:
      - echo "Running TypeScript linters..."
      - docker compose run --rm web yarn lint

  lint:fix:
    desc: Fix linting issues
    cmds:
      - echo "Fixing linting issues..."
      - docker compose run --rm web bundle exec rubocop -a
      - docker compose run --rm web yarn lint:fix

  format:
    desc: Format code
    cmds:
      - echo "Formatting code..."
      - docker compose run --rm web yarn format

  security:check:
    desc: Run security checks
    cmds:
      - echo "Running security checks..."
      - docker compose run --rm web bundle exec brakeman

  console:
    desc: Start Rails console
    cmds:
      - echo "Starting Rails console..."
      - docker compose run --rm web bundle exec rails console

  db:setup:
    desc: Setup database
    cmds:
      - echo "Setting up database..."
      - docker compose run --rm web bundle exec rails db:setup

  db:migrate:
    desc: Run database migrations
    cmds:
      - echo "Running migrations..."
      - docker compose run --rm web bundle exec rails db:migrate

  db:seed:
    desc: Seed database
    cmds:
      - echo "Seeding database..."
      - docker compose run --rm web bundle exec rails db:seed

  frontend:build:
    desc: Build frontend assets
    cmds:
      - echo "Building frontend assets..."
      - docker compose run --rm web yarn build

  frontend:watch:
    desc: Watch frontend assets for changes
    cmds:
      - echo "Watching frontend assets..."
      - docker compose run --rm web yarn watch

  build:
    desc: Build production Docker image
    cmds:
      - echo "Building production Docker image..."
      - docker build -t baseball-league-manager:latest .

  ci:
    desc: Run CI checks locally
    cmds:
      - echo "Running CI checks locally..."
      - task: lint
      - task: security:check
      - task: test
      - task: test:frontend

  deploy:aws:
    desc: Deploy to AWS
    dir: "{{.TERRAFORM_DIR}}/aws"
    cmds:
      - echo "Deploying to AWS..."
      - terraform init
      - terraform apply -auto-approve

  deploy:gcp:
    desc: Deploy to Google Cloud
    dir: "{{.TERRAFORM_DIR}}/gcp"
    cmds:
      - echo "Deploying to Google Cloud..."
      - terraform init
      - terraform apply -auto-approve

  deploy:azure:
    desc: Deploy to Azure
    dir: "{{.TERRAFORM_DIR}}/azure"
    cmds:
      - echo "Deploying to Azure..."
      - terraform init
      - terraform apply -auto-approve

  k8s:apply:
    desc: Apply Kubernetes manifests
    dir: "{{.KUBERNETES_DIR}}"
    cmds:
      - echo "Applying Kubernetes manifests..."
      - kubectl apply -f .

  k8s:delete:
    desc: Delete Kubernetes resources
    dir: "{{.KUBERNETES_DIR}}"
    cmds:
      - echo "Deleting Kubernetes resources..."
      - kubectl delete -f .

  docs:generate:
    desc: Generate documentation
    cmds:
      - echo "Generating documentation..."
      - docker compose run --rm web bundle exec yard doc

  api:docs:generate:
    desc: Generate API documentation
    cmds:
      - echo "Generating API documentation..."
      - docker compose run --rm web bundle exec rails rswag:specs:swaggerize

  clean:
    desc: Clean up development environment
    cmds:
      - echo "Cleaning up..."
      - docker compose down -v
      - docker system prune -f
